name: 'OIDC Debugger'
description: 'Print the GitHub Actions OIDC claims.'
author: 'step-security'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  audience:
    description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/actions-oidc-debugger:v1.0.3@sha256:731f7208bc33c7c15b4c925436976a3bf9bd27c93202513587cd5244a34f7ca3' #v1.0.3
  args:
    - ${{ inputs.audience }}
