name: 'OIDC Debugger'
description: 'Print the GitHub Actions OIDC claims.'
author: 'step-security'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  audience:
    description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/actions-oidc-debugger:v1.0.0@sha256:a1a9273ebe89904f24e1e2b1726e23a4ed402216bf995a94c87961719e353f1a' #v1.0.0
  args:
    - ${{ inputs.audience }}
