name: 'OIDC Debugger'
description: 'Print the GitHub Actions OIDC claims.'
author: 'step-security'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  audience:
    description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/actions-oidc-debugger:v1.0.4@sha256:578fc0993fb4b4881f9ce4e8b0d42620d527f8bf82fc50f20fb661b3e5e5eae4' #v1.0.4
  args:
    - ${{ inputs.audience }}
