---
name: Test Debugger Action
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Debug OIDC Claims
        uses: ./
        with:
          audience: 'https://github.com/step-security'
